package com.hema.newretail.backstage.dao;

import com.hema.newretail.backstage.common.queryparam.data.DataSalesTrendDBCondition;
import com.hema.newretail.backstage.entry.data.DDayMachineUuidEntry;

import java.util.List;

public interface DDayMachineUuidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_day$machineuuid
     *
     * @mbggenerated
     */
    int insert(DDayMachineUuidEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_day$machineuuid
     *
     * @mbggenerated
     */
    int insertSelective(DDayMachineUuidEntry record);


/**
 *
 * 功能描述: 数据统计销量趋势接口
 *
 * @param condition
 * @return List<DDayMachineUuidEntry>
 * @author  cwz
 * @date  2018/12/17 20:29
 */
    List<DDayMachineUuidEntry> selectBaseResultMap(DataSalesTrendDBCondition condition);
}