package com.hema.newretail.backstage.entry.grid;

import java.util.Date;

public class GridSysUserInfoEntry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.login_account
     *
     * @mbggenerated
     */
    private String loginAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.depart_name
     *
     * @mbggenerated
     */
    private String departName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.depart_id
     *
     * @mbggenerated
     */
    private Long departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.position_name
     *
     * @mbggenerated
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.position_id
     *
     * @mbggenerated
     */
    private Long positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.join_time
     *
     * @mbggenerated
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.pic_url
     *
     * @mbggenerated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.login_count
     *
     * @mbggenerated
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.login_ip
     *
     * @mbggenerated
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_sysuser_info.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.id
     *
     * @return the value of grid_sysuser_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.id
     *
     * @param id the value for grid_sysuser_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.login_account
     *
     * @return the value of grid_sysuser_info.login_account
     *
     * @mbggenerated
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.login_account
     *
     * @param loginAccount the value for grid_sysuser_info.login_account
     *
     * @mbggenerated
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.password
     *
     * @return the value of grid_sysuser_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.password
     *
     * @param password the value for grid_sysuser_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.user_name
     *
     * @return the value of grid_sysuser_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.user_name
     *
     * @param userName the value for grid_sysuser_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.nick_name
     *
     * @return the value of grid_sysuser_info.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.nick_name
     *
     * @param nickName the value for grid_sysuser_info.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.sex
     *
     * @return the value of grid_sysuser_info.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.sex
     *
     * @param sex the value for grid_sysuser_info.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.is_deleted
     *
     * @return the value of grid_sysuser_info.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.is_deleted
     *
     * @param isDeleted the value for grid_sysuser_info.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.phone
     *
     * @return the value of grid_sysuser_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.phone
     *
     * @param phone the value for grid_sysuser_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.depart_name
     *
     * @return the value of grid_sysuser_info.depart_name
     *
     * @mbggenerated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.depart_name
     *
     * @param departName the value for grid_sysuser_info.depart_name
     *
     * @mbggenerated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.depart_id
     *
     * @return the value of grid_sysuser_info.depart_id
     *
     * @mbggenerated
     */
    public Long getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.depart_id
     *
     * @param departId the value for grid_sysuser_info.depart_id
     *
     * @mbggenerated
     */
    public void setDepartId(Long departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.position_name
     *
     * @return the value of grid_sysuser_info.position_name
     *
     * @mbggenerated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.position_name
     *
     * @param positionName the value for grid_sysuser_info.position_name
     *
     * @mbggenerated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.position_id
     *
     * @return the value of grid_sysuser_info.position_id
     *
     * @mbggenerated
     */
    public Long getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.position_id
     *
     * @param positionId the value for grid_sysuser_info.position_id
     *
     * @mbggenerated
     */
    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.join_time
     *
     * @return the value of grid_sysuser_info.join_time
     *
     * @mbggenerated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.join_time
     *
     * @param joinTime the value for grid_sysuser_info.join_time
     *
     * @mbggenerated
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.pic_url
     *
     * @return the value of grid_sysuser_info.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.pic_url
     *
     * @param picUrl the value for grid_sysuser_info.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.token
     *
     * @return the value of grid_sysuser_info.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.token
     *
     * @param token the value for grid_sysuser_info.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.note
     *
     * @return the value of grid_sysuser_info.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.note
     *
     * @param note the value for grid_sysuser_info.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.state
     *
     * @return the value of grid_sysuser_info.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.state
     *
     * @param state the value for grid_sysuser_info.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.create_time
     *
     * @return the value of grid_sysuser_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.create_time
     *
     * @param createTime the value for grid_sysuser_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.modify_time
     *
     * @return the value of grid_sysuser_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.modify_time
     *
     * @param modifyTime the value for grid_sysuser_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.create_by
     *
     * @return the value of grid_sysuser_info.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.create_by
     *
     * @param createBy the value for grid_sysuser_info.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.login_count
     *
     * @return the value of grid_sysuser_info.login_count
     *
     * @mbggenerated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.login_count
     *
     * @param loginCount the value for grid_sysuser_info.login_count
     *
     * @mbggenerated
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.login_time
     *
     * @return the value of grid_sysuser_info.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.login_time
     *
     * @param loginTime the value for grid_sysuser_info.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.login_ip
     *
     * @return the value of grid_sysuser_info.login_ip
     *
     * @mbggenerated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.login_ip
     *
     * @param loginIp the value for grid_sysuser_info.login_ip
     *
     * @mbggenerated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_sysuser_info.company_id
     *
     * @return the value of grid_sysuser_info.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_sysuser_info.company_id
     *
     * @param companyId the value for grid_sysuser_info.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}