package com.hema.newretail.backstage.entry.data;
/**
 *
 * 功能描述: BaseBoxGroupEntry

 * @author  cwz
 * @date  2018/12/10 10:41
 */
public class DDayMachineUuidEntry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_day$machineuuid.dimension
     *
     * @mbggenerated
     */
    private String dimension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_day$machineuuid.day
     *
     * @mbggenerated
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_day$machineuuid.machineUuid
     *
     * @mbggenerated
     */
    private String machineuuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_day$machineuuid.dimension
     *
     * @return the value of d_day$machineuuid.dimension
     *
     * @mbggenerated
     */
    public String getDimension() {
        return dimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_day$machineuuid.dimension
     *
     * @param dimension the value for d_day$machineuuid.dimension
     *
     * @mbggenerated
     */
    public void setDimension(String dimension) {
        this.dimension = dimension == null ? null : dimension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_day$machineuuid.day
     *
     * @return the value of d_day$machineuuid.day
     *
     * @mbggenerated
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_day$machineuuid.day
     *
     * @param day the value for d_day$machineuuid.day
     *
     * @mbggenerated
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_day$machineuuid.machineUuid
     *
     * @return the value of d_day$machineuuid.machineUuid
     *
     * @mbggenerated
     */
    public String getMachineuuid() {
        return machineuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_day$machineuuid.machineUuid
     *
     * @param machineuuid the value for d_day$machineuuid.machineUuid
     *
     * @mbggenerated
     */
    public void setMachineuuid(String machineuuid) {
        this.machineuuid = machineuuid == null ? null : machineuuid.trim();
    }
}